In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('OmicsExpressionProteinCodingGenesTPMLogp1.csv')

In [4]:
display(df.head())

,Unnamed: 0,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),C1orf112 (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),...,H3C2 (8358),H3C3 (8352),AC098582.1 (8916),DUS4L-BCAP29 (115253422),C8orf44-SGK3 (100533105),ELOA3B (728929),NPBWR1 (2831),ELOA3D (100506888),ELOA3 (162699),CDR1 (1038)
0,ACH-001113,4.331992,0.000000,7.364660,2.792855,4.471187,0.028569,1.226509,3.044394,6.500005,...,2.689299,0.189034,0.201634,2.130931,0.555816,0.0,0.275007,0.0,0.0,0.000000
1,ACH-001289,4.567424,0.584963,7.106641,2.543496,3.504620,0.000000,0.189034,3.813525,4.221877,...,1.286881,1.049631,0.321928,1.464668,0.632268,0.0,0.014355,0.0,0.0,0.000000
2,ACH-001339,3.150560,0.000000,7.379118,2.333424,4.228049,0.056584,1.310340,6.687201,3.682573,...,0.594549,1.097611,0.831877,2.946731,0.475085,0.0,0.084064,0.0,0.0,0.042644
3,ACH-001979,4.240314,0.000000,5.681168,2.063503,1.641546,0.000000,7.236301,5.948367,4.596935,...,0.000000,0.000000,0.847997,1.887525,0.176323,0.0,0.000000,0.0,0.0,0.000000
4,ACH-002438,4.032101,0.000000,6.674687,2.117695,3.003602,0.000000,2.169925,6.838195,3.253989,...,0.238787,0.378512,0.584963,1.748461,0.839960,0.0,0.014355,0.0,0.0,0.042644

In [7]:
df2 = pd.read_csv('OmicsSomaticMutations.csv', index_col=0)

/var/folders/r9/tk3nsgjj4_j4z3n_rxsd7s580000gn/T/ipykernel_37648/2222604753.py:1: DtypeWarning: Columns (22,50,56,57,58,59,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('OmicsSomaticMutations.csv', index_col=0)

In [9]:
display(df2.head())

,Pos,Ref,Alt,AF,DP,RefCount,AltCount,GT,PS,VariantType,...,GwasPmID,GtexGene,ProveanPrediction,AMClass,AMPathogenicity,Rescue,RescueReason,ModelID,Hotspot,EntrezGeneID
Chrom,,,,,,,,,,,,,,,,,,,,,
chr1,818203,G,A,0.240,27,21,6,0/1,NaN,SNV,...,NaN,NaN,NaN,NaN,NaN,False,NaN,ACH-000062,False,400728.0
chr1,851926,G,A,0.158,17,15,2,0/1,NaN,SNV,...,NaN,NaN,NaN,NaN,NaN,False,NaN,ACH-001949,False,643837.0
chr1,924510,GC,AA,0.412,35,21,14,0|1,924510.0,substitution,...,NaN,NaN,NaN,NaN,NaN,False,NaN,ACH-000402,False,148398.0
chr1,924657,C,G,0.437,17,9,8,0/1,NaN,SNV,...,NaN,NaN,NaN,NaN,NaN,False,NaN,ACH-000693,False,148398.0
chr1,924750,C,T,0.625,19,7,12,0/1,NaN,SNV,...,NaN,NaN,NaN,NaN,NaN,False,NaN,ACH-000930,False,148398.0